# -*- coding: utf-8 -*-
"""Generating_Images

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJAvxFx_EiS_-QoM2SxxtUEosskBCX-T
"""

!pip install --upgrade diffusers transformers accelerate safetensors

from huggingface_hub import notebook_login
notebook_login()

from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

prompt = "image of a zoo"
image = pipe(prompt).images[0]

# Save image inside Colab
image.save("output.png")

# Download to your computer
from google.colab import files
files.download("output.png")

